# Hugo
title = "EpicServer Documentation"
description = "Documentation for EpicServer - A powerful Go web server"
images = ["cover.png"]

# mainSections
mainSections = ["docs"]

[social]
  twitter = "getdoks"

# Doks (@thulite/doks-core)
[doks]
  # Color mode
  colorMode = "auto"
  colorModeToggler = true

  # Navbar
  navbarSticky = true
  containerBreakpoint = "lg"

  ## Button
  navBarButton = false
  navBarButtonUrl = "/docs/prologue/introduction/"
  navBarButtonText = "Get started"

  # FlexSearch
  flexSearch = true
  searchExclKinds = []
  searchExclTypes = []
  showSearch = []
  indexSummary = false

  ## Search results
  showDate = false
  showSummary = true
  searchLimit = 99

  # Global alert
  alert = false
  alertDismissable = true

  # Bootstrap
  bootstrapJavascript = false

  # Nav
  sectionNav = ["docs"]
  toTopButton = true
  breadcrumbTrail = true
  headlineHash = true
  scrollSpy = true

  # Multilingual
  multilingualMode = false
  showMissingLanguages = true

  # Versioning
  docsVersioning = false
  docsVersion = "1.0"

  # UX
  headerBar = true
  backgroundDots = true

  # Homepage
  sectionFooter = true

  # Blog
  relatedPosts = false
  imageList = true
  imageSingle = true

  # Repository
  editPage = false
  lastMod = true
  repoHost = "GitHub"
  docsRepo = "https://github.com/h-enk/doks"
  docsRepoBranch = "main"
  docsRepoSubPath = ""

  # SCSS colors
  ## Dark theme
  ## Light theme

  [doks.menu]
    [doks.menu.section]
      auto = true
      collapsibleSidebar = true

# Debug
[render_hooks.image]
  errorLevel = 'ignore'

[render_hooks.link]
  errorLevel = 'ignore'
  highlightBroken = false

# Images (@thulite/images)
[thulite_images]
  [thulite_images.defaults]
    decoding = "async"
    fetchpriority = "auto"
    loading = "lazy"
    widths = [480, 576, 768, 1025, 1200, 1440]
    sizes = "auto"
    process = ""
    lqip = "16x webp q20"

# Inline SVG (@thulite/inline-svg)
[inline_svg]
  iconSetDir = "tabler-icons"

# SEO (@thulite/seo)
[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png"
    svgIcon = "favicon.svg"
    maskIcon = "mask-icon.svg"
    maskIconColor = "white"
  [seo.schemas]
    type = "Organization"
    logo = "favicon-512x512.png"
    name = "Thulite"
    sameAs = []
    images = ["cover.png"]
    article = []
    newsArticle = []
    blogPosting = ["blog"]
    product = []
