name: Test Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        # Exclude test helper files from coverage calculation
        go test -race -covermode atomic -coverprofile=covprofile.raw ./...
        # Filter out test helper files from coverage report
        cat covprofile.raw | grep -v "helpers_test.go" > covprofile
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github